### ISSUE TITLE
Strawpoll

### ISSUE THREAD

**Issue by noLogica** [VespyrLeague/vespyr-nodecg#20]
Hi @Chr12t0pher,

I remember that i've tested your awesome work a couple weeks ago and everything was fine, but now something change (content type?) and creating a pool is broken.

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at F:\nodejs\nodecg\bundles\strawpoll\extension\strawpoll.js:35:25
    at ConcatStream.<anonymous> (F:\nodejs\nodecg\bundles\strawpoll\node_modules\concat-stream\index.js:36:43)
    at emitNone (events.js:85:20)
    at ConcatStream.emit (events.js:179:7)
    at finishMaybe (F:\nodejs\nodecg\bundles\strawpoll\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at endWritable (F:\nodejs\nodecg\bundles\strawpoll\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at ConcatStream.Writable.end (F:\nodejs\nodecg\bundles\strawpoll\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at DuplexWrapper.onend (F:\nodejs\nodecg\bundles\strawpoll\node_modules\duplexer2\node_modules\readable-stream\lib\_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:273:16)
```

Just trying to help with some feedback since this is over my league eheh

Cheers

**Comment by Chr12t0pher** [comment]
Hey there - it looks like you're using just the strawpoll functionality right? (that's fine)

Anyway I've had a couple of problems with strawpoll part myself recently - although I haven't been able to get a log like you so thanks! 

The temp/hacky fix is to just wrap the `var stream = get(...` block in a try catch block, it's been working okay for me so far.

**Comment by noLogica** [comment]
Thanks for the fast replay, I'll give it a try :D
Yeah I was getting some nodecg disconnetions so I insulated the strawpoll module trying to experiment with it.
But the rest of your bundle was working great :)

ps: i've also removed `permissive: true` options and fixed people being able to dupe votes
